#!/usr/bin/env bash

main() {
    rm -rf ./public/.well-known/
    mkdir -p ./public/.well-known/openpgpkey/

    local keys=($(grep '^[^#]' "./keys.conf"))
    cd ./public/.well-known/

    gpg --list-options show-only-fpr-mbox -k ${keys[@]} | gpg-wks-client -v --install-key
}

main
